targetScope = 'resourceGroup'

@description('Environment name used to build unique resource names (e.g. dev, prod).')
@minLength(1)
@maxLength(12)
param environmentName string = 'photoalbum'

@description('Primary location for all resources.')
param location string = resourceGroup().location

@description('Location for the PostgreSQL flexible server. Must have available capacity/quota.')
param postgresLocation string = location

@description('Name of the application database.')
param databaseName string = 'photoalbum'

@description('PostgreSQL administrator login name.')
param postgresAdministratorLogin string = 'pgadmin'

@description('PostgreSQL administrator password. Generated by the deployment script; the application itself uses managed identity.')
@secure()
param postgresAdministratorLoginPassword string

@description('Object ID of the Microsoft Entra principal to set as PostgreSQL administrator.')
param entraAdminObjectId string

@description('Principal name (UPN) of the Microsoft Entra PostgreSQL administrator.')
param entraAdminName string

@description('Principal type of the Microsoft Entra PostgreSQL administrator.')
@allowed([
  'User'
  'Group'
  'ServicePrincipal'
])
param entraAdminType string = 'User'

@description('Port the application container listens on.')
param targetPort int = 8080

@description('Create the AcrPull role assignment for the managed identity. Set to false only when the deploying principal lacks Microsoft.Authorization/roleAssignments/write; the container app then falls back to ACR admin credentials.')
param assignAcrPullRole bool = true

@description('Tags applied to all resources.')
param tags object = {
  'azd-env-name': environmentName
  application: 'photo-album'
  managedBy: 'bicep'
}

var resourceToken = uniqueString(subscription().id, resourceGroup().id, location, environmentName)

var logAnalyticsName = 'azlaw${resourceToken}'
var identityName = 'azid${resourceToken}'
var containerRegistryName = 'azcr${resourceToken}'
var containerAppsEnvName = 'azcae${resourceToken}'
var containerAppName = 'azca${resourceToken}'
var postgresServerName = 'azpg${resourceToken}'

module logAnalytics 'modules/loganalytics.bicep' = {
  name: 'loganalytics-deployment'
  params: {
    name: logAnalyticsName
    location: location
    tags: tags
  }
}

module identity 'modules/identity.bicep' = {
  name: 'identity-deployment'
  params: {
    name: identityName
    location: location
    tags: tags
  }
}

// Container registry + AcrPull role assignment (declared before the container app).
module containerRegistry 'modules/containerregistry.bicep' = {
  name: 'containerregistry-deployment'
  params: {
    name: containerRegistryName
    location: location
    tags: tags
    acrPullPrincipalId: identity.outputs.principalId
    assignAcrPullRole: assignAcrPullRole
  }
}

module postgres 'modules/postgresql.bicep' = {
  name: 'postgresql-deployment'
  params: {
    name: postgresServerName
    location: postgresLocation
    tags: tags
    databaseName: databaseName
    administratorLogin: postgresAdministratorLogin
    administratorLoginPassword: postgresAdministratorLoginPassword
    entraAdminObjectId: entraAdminObjectId
    entraAdminName: entraAdminName
    entraAdminType: entraAdminType
  }
}

module containerApp 'modules/containerapp.bicep' = {
  name: 'containerapp-deployment'
  params: {
    environmentName: containerAppsEnvName
    containerAppName: containerAppName
    location: location
    tags: tags
    logAnalyticsWorkspaceId: logAnalytics.outputs.id
    logAnalyticsCustomerId: logAnalytics.outputs.customerId
    userAssignedIdentityId: identity.outputs.id
    userAssignedIdentityClientId: identity.outputs.clientId
    containerRegistryLoginServer: containerRegistry.outputs.loginServer
    containerRegistryName: containerRegistry.outputs.name
    useRegistryAdminCredentials: !assignAcrPullRole
    targetPort: targetPort
  }
  dependsOn: [
    containerRegistry
  ]
}

output AZURE_LOCATION string = location
output AZURE_TENANT_ID string = subscription().tenantId
output AZURE_RESOURCE_GROUP string = resourceGroup().name

output AZURE_CONTAINER_REGISTRY_NAME string = containerRegistry.outputs.name
output AZURE_CONTAINER_REGISTRY_ENDPOINT string = containerRegistry.outputs.loginServer
output AZURE_ACR_PULL_ROLE_ASSIGNED bool = assignAcrPullRole

output AZURE_CONTAINER_APPS_ENVIRONMENT_NAME string = containerApp.outputs.environmentName
output AZURE_CONTAINER_APP_NAME string = containerApp.outputs.containerAppName
output AZURE_CONTAINER_NAME string = containerApp.outputs.containerName
output AZURE_CONTAINER_APP_URI string = containerApp.outputs.uri

output AZURE_POSTGRES_SERVER_NAME string = postgres.outputs.name
output AZURE_POSTGRES_FQDN string = postgres.outputs.fqdn
output AZURE_POSTGRES_DATABASE_NAME string = postgres.outputs.databaseName
output AZURE_POSTGRES_LOCATION string = postgresLocation

output AZURE_MANAGED_IDENTITY_NAME string = identity.outputs.name
output AZURE_MANAGED_IDENTITY_CLIENT_ID string = identity.outputs.clientId
output AZURE_LOG_ANALYTICS_NAME string = logAnalytics.outputs.name
